name: Gradle Build

on:
  push:
    branches:
      - "main"
      - "package-by-*"
    paths-ignore:
      - '.gitignore'
      - '.sdkmanrc'
      - 'README.md'
      - 'LICENSE'
      - 'Taskfile.yml'
      - 'renovate.json'
      - 'k8s/**'
      - 'kind/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
